type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Movie @table {
  title: String!
  releaseYear: Int!
  createdAt: Timestamp!
  plotSummary: String
  posterUrl: String
  genre: String
  director: String
}

type Rating @table(key: ["user", "movie"]) {
  score: Int!
  createdAt: Timestamp!
  reviewText: String
  updatedAt: Timestamp
  user: User!
  movie: Movie!
}

type WatchlistEntry @table(key: ["user", "movie"]) {
  createdAt: Timestamp!
  user: User!
  movie: Movie!
}